// src/TemplatePDFGenerator.js
import { jsPDF } from 'jspdf';

export const generateTemplatePDF = () => {
  const doc = new jsPDF();
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('Wedding Guest List Template', 105, 20, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text('Instructions:', 20, 35);
  doc.setFontSize(10);
  doc.text('1. Use this template to create your wedding guest list.', 25, 45);
  doc.text('2. You can also upload a CSV file with the same column headers to import guests into the app.', 25, 52);
  doc.text('3. Required columns: Name, Email, Phone, Address', 25, 59);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Guest Information', 20, 75);
  const headers = ['Name', 'Email', 'Phone', 'Address', 'Invitation Status'];
  const columnWidths = [40, 40, 30, 50, 30];
  let startY = 85;
  let startX = 20;
  headers.forEach((header, index) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(header, startX, startY);
    startX += columnWidths[index];
  });
  doc.setLineWidth(0.5);
  doc.line(20, startY + 2, 190, startY + 2);
  startY += 10;
  for (let i = 0; i < 20; i++) {
    startX = 20;
    headers.forEach((_, index) => { // eslint-disable-line no-loop-func
      doc.rect(startX, startY - 6, columnWidths[index], 10, 'S');
      startX += columnWidths[index];
    });
    startY += 10;
  }
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Aisle Be There - Wedding Guest List Manager', 105, 280, { align: 'center' });
  doc.save('wedding_guest_template.pdf');
};

export const generateTemplateCSV = () => {
  const headers = ['name', 'email', 'phone', 'address'];
  const exampleRow = ['John Doe', 'john@example.com', '555-123-4567', '"123 Main St, Anytown, ST 12345"'];
  const csvContent = [headers.join(','), exampleRow.join(',')].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', 'wedding_guest_template.csv');
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};